# Generated by Django 4.2.13 on 2024-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_field', models.BooleanField(default=False)),
                ('text_field', models.TextField(default='')),
                ('int_field', models.IntegerField(default=0)),
                ('float_field', models.FloatField(default=0)),
            ],
        ),
    ]
